# HigherSelf Network Server - Development Override Configuration
# This file provides development-specific overrides for docker-compose.unified.yml
# Automatically loaded by Docker Compose for local development

version: '3.8'

services:
  # Development overrides for main application server
  higherself-server:
    build:
      target: development  # Use development build stage if available
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - SERVER_RELOAD=true
      - TESTING=false
      - ENVIRONMENT=development
      - MULTI_ENTITY_MODE=true
      - PRIMARY_BUSINESS_ENTITY=the_7_space
      
      # Development database settings
      - MONGODB_DB_NAME=higherself_dev
      - REDIS_DB=0
      
      # Development feature flags
      - ENABLE_DEBUG_ENDPOINTS=true
      - ENABLE_EXPERIMENTAL_FEATURES=true
      - ENABLE_PERFORMANCE_TESTING=false
      - DISABLE_WEBHOOKS=false
      
      # Development secrets (not for production)
      - SECRETS_BACKEND=env_file
      - ENABLE_SECRETS_ROTATION=false
    ports:
      - "8000:8000"  # Direct port mapping for development
      - "8443:8443"  # HTTPS port for testing
    volumes:
      # Add source code mounting for hot reload (development only)
      - .:/app:cached
      - ./logs/dev:/app/logs
      - ./data/dev:/app/data
      - ./config:/app/config:ro
    command: >
      uvicorn main:app 
      --host 0.0.0.0 
      --port 8000 
      --reload 
      --log-level debug
      --reload-dir /app
      --reload-exclude /app/logs
      --reload-exclude /app/data

  # Development worker with reduced concurrency
  celery-worker:
    environment:
      - CELERY_WORKER_CONCURRENCY=2
      - CELERY_WORKER_LOGLEVEL=debug
      - ENVIRONMENT=development
    volumes:
      - .:/app:cached  # Source code mounting for development

  # Development scheduler
  celery-beat:
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app:cached  # Source code mounting for development

  # Development MongoDB with reduced resources
  mongodb:
    ports:
      - "27017:27017"  # Expose port for development tools
    environment:
      - MONGO_INITDB_DATABASE=higherself_dev
    command:
      - "--auth"
      - "--bind_ip_all"
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
      - "--logappend"
      - "--wiredTigerCacheSizeGB"
      - "0.5"  # Reduced cache for development

  # Development Redis with no password for simplicity
  redis:
    ports:
      - "6379:6379"  # Expose port for development tools
    command: redis-server /usr/local/etc/redis/redis.conf --loglevel debug

  # Development Consul
  consul:
    ports:
      - "8500:8500"  # Expose UI for development
    command: >
      agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 
      -data-dir=/consul/data -log-file=/consul/logs/consul.log
      -log-level=DEBUG

  # Development Prometheus with shorter retention
  prometheus:
    ports:
      - "9090:9090"  # Expose for development access
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.retention.time=7d"  # Shorter retention for dev
      - "--web.enable-admin-api"
      - "--log.level=debug"

  # Development Grafana
  grafana:
    ports:
      - "3000:3000"  # Expose for development access
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Simple password for dev
      - GF_LOG_LEVEL=debug
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel

  # Development Nginx with simpler configuration
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deployment/nginx/ssl-dev:/etc/nginx/ssl:ro

  # Development Vault (optional)
  vault:
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-root-token
      - VAULT_LOG_LEVEL=debug
    ports:
      - "8200:8200"  # Expose for development access

# Development-specific volumes (smaller, faster)
volumes:
  mongodb_data_dev:
    driver: local
  redis_data_dev:
    driver: local
  consul_data_dev:
    driver: local
  prometheus_data_dev:
    driver: local
  grafana_data_dev:
    driver: local
  vault_data_dev:
    driver: local

# Development network configuration
networks:
  higherself_network:
    driver: bridge
    name: higherself-network-dev
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
