version: '3.8'

services:
  windsurf-agent:
    restart: always
    environment:
      - LOG_LEVEL=INFO
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # No ports exposed directly - only through Nginx
    ports: []
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  nginx:
    restart: always
    volumes:
      - ./deployment/docker-nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./deployment/ssl:/etc/nginx/ssl:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
