apiVersion: 1

datasources:
  - name: Prometheus-Demo
    type: prometheus
    access: proxy
    url: http://prometheus-demo:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}
    version: 1
