name: Update Architecture Visualization

on:
  push:
    branches: [ main ]
    paths:
      - 'services/**/*.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-visualization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update architecture file
        run: echo "Architecture visualization updated" > architecture/update_log.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: 'Update architecture visualization [automated]'
          add: 'architecture/update_log.txt'
